AWSTemplateFormatVersion: "2010-09-09"
Description: "Main CloudFormation stack for VPC and EKS"

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    #DeletionPolicy: Retain
    Properties:
      TemplateURL: https://cloudformation-template-sourcecode.s3.ap-southeast-1.amazonaws.com/vpc-stack.yaml

  EKSStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    Properties:
      TemplateURL: https://cloudformation-template-sourcecode.s3.ap-southeast-1.amazonaws.com/eks-stack.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        Subnets: !Join [",", [!GetAtt VPCStack.Outputs.PrivateSubnetId1, !GetAtt VPCStack.Outputs.PrivateSubnetId2]]
        ClusterControlPlaneSecurityGroup: !GetAtt VPCStack.Outputs.ControlPlaneSecurityGroupId
        MultusSubnet: !Join [",", [!GetAtt VPCStack.Outputs.PrivateSubnetId1]]
        MultusSecurityGroup: !Join [",", [!GetAtt VPCStack.Outputs.MultusSecurityGroup]]

  # OIDCProviderLookupStack:
  #   Type: AWS::CloudFormation::Stack
  #   DeletionPolicy: Retain
  #   DependsOn: EKSStack
  #   Properties:
  #     TemplateURL: https://cloudformation-template-cft.s3.ap-south-1.amazonaws.com/oidc-fetch-lambda.yml
  #     Parameters:
  #       ClusterName: !GetAtt EKSStack.Outputs.EKSClusterName
  #       Region: !Ref "AWS::Region"
  #       LambdaS3Bucket: cloudformation-template-cft
  #       LambdaS3Key: oidc-lambda.zip

  # ALBControllerStack:
  #   Type: AWS::CloudFormation::Stack
  #   DeletionPolicy: Retain
  #   DependsOn: OIDCProviderLookupStack
  #   Properties:
  #     TemplateURL: https://cloudformation-template-cft.s3.ap-south-1.amazonaws.com/alb-controller.yml
  #     Parameters:
  #       VpcId: !GetAtt VPCStack.Outputs.VpcId
  #       ClusterName: !GetAtt EKSStack.Outputs.EKSClusterName
  #       PublicSubnetIds: !GetAtt VPCStack.Outputs.PublicSubnetIds
  #       OIDCProviderId: !GetAtt OIDCProviderLookupStack.Outputs.OIDCProviderId
